/**
 * Word Warriors — Internal Word Bank
 * ~2200 common English words (2-8 letters) for offline validation.
 * No API calls needed — all validation is done client-side.
 *
 * Special combat categories overlay on top of the base word list.
 * Any word in COMBAT_CATEGORIES is also automatically in VALID_WORDS.
 */

// ─────────────────────────────────────────────────────────────────────────────
// COMBAT CATEGORIES  —  special words that trigger game effects
// ─────────────────────────────────────────────────────────────────────────────
const COMBAT_CATEGORIES = {
  ATTACK: {
    words: new Set([
      'slash','strike','smite','pierce','crush','blast','stab','hack','cut','wound',
      'maim','slay','smash','bash','punch','kick','bite','claw','tear','rend',
      'split','dice','chop','cleave','impale','gore','mangle','ram','gut','sever',
      'assault','attack','charge','rush','lunge','thrust','war','battle','combat',
      'fight','duel','raid','siege','ambush','sword','blade','knife','axe','spear',
      'lance','arrow','bow','club','mace','fist','rage','fury','wrath','strike',
      'beat','bludgeon','batter','pummel','trounce','vanquish','rout','fell',
      'kill','slay','murder','execute','annihilate','destroy','obliterate','demolish',
      'shatter','wreck','ravage','pillage','plunder','ravish','slaughter','massacre',
      'hunt','stalk','trap','snare','ambush','intercept','flank',
    ]),
    effect: 'ATTACK',
    multiplier: 1.5,
    label: '⚔️ WARRIOR WORD',
    description: '+50% Damage!',
    color: '#ff5555',
    bgColor: 'rgba(200,0,0,0.3)',
  },
  HEAL: {
    words: new Set([
      'heal','cure','mend','rest','life','revive','restore','health','salve',
      'herb','balm','tonic','elixir','potion','remedy','ease','renew','refresh',
      'rebirth','vitality','vigor','boon','solace','comfort','soothe','tend',
      'nurse','aide','help','aid','pray','faith','grace','light','hope','mercy',
      'mend','bind','stitch','bandage','splint','recuperate','recover','rebound',
    ]),
    effect: 'HEAL',
    multiplier: 0,
    label: '💚 HEALING WORD',
    description: 'Restores HP!',
    color: '#44ff88',
    bgColor: 'rgba(0,200,80,0.3)',
  },
  SHIELD: {
    words: new Set([
      'shield','guard','block','defend','ward','protect','armor','wall','barrier',
      'deflect','parry','dodge','evade','resist','repel','buckler','plate',
      'mail','carapace','bunker','fortress','bulwark','rampart','castle','bastion',
      'aegis','cover','shelter','hide','brace','fortify','reinforce',
      'steel','harden','toughen',
    ]),
    effect: 'SHIELD',
    multiplier: 0,
    label: '🛡️ SHIELD WORD',
    description: 'Gains Shield!',
    color: '#4488ff',
    bgColor: 'rgba(0,60,200,0.3)',
  },
  FIRE: {
    words: new Set([
      'fire','flame','burn','blaze','scorch','char','heat','inferno','ember',
      'ash','ignite','kindle','torch','pyre','lava','magma','solar','flare',
      'forge','brand','sear','smolder','cinder','coal','volcanic','eruption',
      'furnace','hellfire','wildfire','bonfire','firestorm','conflagration',
      'phoenix','dragon','meteor','comet','radiance','solar','nova',
    ]),
    effect: 'BURN',
    multiplier: 1.25,
    label: '🔥 FIRE WORD',
    description: '+25% Dmg + Burn!',
    color: '#ff8844',
    bgColor: 'rgba(220,80,0,0.3)',
  },
  ICE: {
    words: new Set([
      'ice','frost','freeze','chill','cold','snow','blizzard','arctic','glacier',
      'tundra','frozen','hail','sleet','frigid','polar','crystal','freeze',
      'slush','rime','permafrost','snowstorm','iceberg','floe','drift',
      'numb','still','suspend','trap','encase','solidify',
    ]),
    effect: 'FREEZE',
    multiplier: 1.25,
    label: '❄️ ICE WORD',
    description: '+25% Dmg + Freeze!',
    color: '#88ddff',
    bgColor: 'rgba(0,120,220,0.3)',
  },
  LIGHTNING: {
    words: new Set([
      'shock','zap','bolt','spark','thunder','storm','surge','jolt','volt',
      'arc','flash','current','charge','static','plasma','electric','overload',
      'discharge','tesla','capacitor','amp','watt','ohm','circuit','short',
      'fry','blast','crack','boom','crash','roar','smite','strike',
    ]),
    effect: 'STUN',
    multiplier: 1.25,
    label: '⚡ LIGHTNING WORD',
    description: '+25% Dmg + Stun!',
    color: '#ffff44',
    bgColor: 'rgba(200,200,0,0.3)',
  },
  POISON: {
    words: new Set([
      'poison','venom','toxic','plague','blight','rot','decay','wither','corrode',
      'fester','putrid','miasma','stench','bile','plague','virus','bacteria',
      'fungus','mold','spore','slime','ooze','sludge','waste','sewer',
      'acid','caustic','corrosive','noxious','pestilence','contagion','infection',
      'disease','taint','tarnish','rust','oxidize',
    ]),
    effect: 'POISON',
    multiplier: 1.0,
    label: '☠️ POISON WORD',
    description: 'Poisons enemy! (3HP/turn)',
    color: '#88ff44',
    bgColor: 'rgba(80,180,0,0.3)',
  },
  DARK: {
    words: new Set([
      'death','doom','dark','shadow','void','abyss','dread','fear','despair',
      'terror','malice','spite','wraith','specter','phantom','ghost','soul',
      'grim','bleak','dusk','night','cursed','hex','evil','sinister','wicked',
      'vile','corrupt','taint','bane','curse','woe','grief','anguish','torment',
      'suffer','agony','pain','plague','ruin','havoc','chaos','anarchy',
      'darkness','eclipse','oblivion','nil','nullify','drain','steal','leech',
      'vampire','lich','undead','revenant','banshee','demon','devil','fiend',
    ]),
    effect: 'LIFESTEAL',
    multiplier: 1.25,
    label: '🌑 DARK WORD',
    description: '+25% Dmg + Lifesteal!',
    color: '#bb66ff',
    bgColor: 'rgba(120,0,200,0.3)',
  },
  NATURE: {
    words: new Set([
      'leaf','vine','root','thorn','seed','grow','bloom','forest','earth',
      'stone','branch','herb','moss','fern','wood','bark','petal','flora',
      'fauna','tree','grass','river','spring','gale','wind','breeze','tide',
      'wave','rain','dew','mist','grove','meadow','field','mountain','valley',
      'stream','brook','pond','lake','ocean','sea','sky','cloud','sun','moon',
      'star','wild','primal','verdant','lush','thicket','canopy','soil',
    ]),
    effect: 'NATURE',
    multiplier: 1.0,
    label: '🌿 NATURE WORD',
    description: 'Small Heal + Attack!',
    color: '#44ff66',
    bgColor: 'rgba(0,180,60,0.3)',
  },
  ARCANE: {
    words: new Set([
      'spell','rune','glyph','ward','charm','bind','seal','magic','mana',
      'arcane','mystic','occult','ritual','sigil','power','force','energy',
      'nexus','flux','phase','rift','portal','gate','vortex','teleport',
      'transmute','enchant','imbue','infuse','invoke','conjure','summon',
      'banish','dispel','nullify','absorb','reflect','mirror','echo',
      'amplify','multiply','double','triple','boost','surge','overflow',
    ]),
    effect: 'ARCANE',
    multiplier: 1.35,
    label: '✨ ARCANE WORD',
    description: '+35% Dmg + Mana Drain!',
    color: '#dd88ff',
    bgColor: 'rgba(180,0,220,0.3)',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// VALID WORDS  —  common English words, 2-8 letters
// ─────────────────────────────────────────────────────────────────────────────
const VALID_WORDS_LIST = [
  // 2-letter
  'ab','ad','ae','ag','ah','ai','al','am','an','ar','as','at','aw','ax','ay',
  'ba','be','bi','bo','by','da','do','ed','ef','eh','el','em','en','er','es',
  'et','ex','fa','gi','go','ha','he','hi','hm','ho','id','if','in','is','it',
  'jo','ka','ki','la','li','lo','ma','me','mi','mo','mu','my','na','ne','no',
  'nu','ob','od','oe','of','oh','oi','ok','om','on','oo','op','or','os','ow',
  'ox','oy','pa','pe','pi','po','qi','re','sh','si','so','ta','ti','to','uh',
  'um','un','up','us','we','wo','xi','xu','ya','ye','yo','za',
  // 3-letter
  'ace','act','add','ado','ads','age','ago','aid','aim','air','ale','all','and',
  'ant','ape','apt','arc','are','ark','arm','art','ash','ask','ate','awe','axe',
  'aye','bad','bag','ban','bar','bat','bay','bed','bet','big','bit','bog','boo',
  'bow','box','boy','bud','bug','bun','bus','but','buy','bye','cab','can','cap',
  'car','cat','cop','cot','cow','cry','cup','cut','dab','dam','day','den','dew',
  'did','dig','dim','dip','dog','dot','dry','dub','dug','dye','ear','eat','egg',
  'ego','elf','elk','elm','emu','end','era','eve','ewe','eye','fad','fan','far',
  'fat','fax','fed','fee','few','fib','fig','fit','fix','fly','foe','fog','for',
  'fox','fry','fun','fur','gap','gas','get','gig','gin','gnu','god','got','gum',
  'gun','gut','guy','gym','had','hag','ham','has','hat','hay','her','hew','hid',
  'him','his','hit','hob','hog','hop','hot','how','hub','hug','hum','hut','icy',
  'ill','imp','ink','inn','ion','ire','ivy','jab','jag','jam','jar','jaw','jet',
  'jig','job','jog','joy','jug','jut','keg','key','kid','kit','lab','lag','lap',
  'law','lax','lay','lea','leg','let','lid','lip','log','lot','low','lug','mad',
  'map','mar','mat','maw','may','men','mob','mod','mom','mop','mow','mud','mug',
  'nab','nag','nap','net','new','nil','nip','nit','nob','nod','nor','not','now',
  'nun','oaf','oak','oar','oat','odd','ode','off','old','opt','orb','ore','our',
  'out','owe','owl','own','pad','pan','pap','par','pat','paw','pay','pea','peg',
  'pen','per','pet','pie','pig','pin','pit','ply','pod','pop','pot','pox','pro',
  'pub','pun','pup','put','rag','ran','rap','rat','raw','ray','red','ref','rep',
  'rev','rib','rid','rig','rim','rip','rob','rod','rot','row','rub','rug','rum',
  'run','rut','sad','sag','sap','sat','saw','say','sea','set','sew','she','shy',
  'sin','sip','sir','sit','ski','sky','sly','sob','son','sot','sow','soy','spa',
  'spy','sty','sub','sum','sun','tab','tad','tan','tap','tar','tax','tea','ten',
  'the','tie','tin','tip','toe','too','top','tow','toy','try','tub','tug','two',
  'urn','van','vat','via','vim','vow','wad','war','was','wax','way','web','wed',
  'wet','who','why','wig','win','wit','woe','wok','won','woo','wow','yak','yam',
  'yap','yaw','yea','yet','yin','you','yow','zoo',
  // 4-letter
  'able','ache','acid','acre','aged','agog','also','alto','amid','amps','arch',
  'area','army','arts','ashy','atom','aunt','auto','avid','away','awed','babe',
  'back','bake','bald','bale','ball','bane','bang','bank','bare','bark','barn',
  'base','bash','bask','bead','beak','beam','bean','bear','beat','beef','beer',
  'bell','belt','best','bill','bird','blab','blah','blot','blue','blur','boar',
  'boat','body','bold','bolt','bond','bone','book','boom','boot','bore','boss',
  'both','bout','brag','brat','brew','brim','brisk','bull','bump','burp','burr',
  'busy','buzz','cafe','cage','cake','calf','call','calm','camp','cane','cant',
  'card','care','carp','cart','case','cash','cast','cave','cell','cent','chad',
  'chef','chin','chip','cite','city','clad','clam','clap','clay','clip','coal',
  'coat','coax','code','coil','coin','coke','cold','cole','come','cone','cook',
  'cool','core','corn','cost','cozy','cram','crap','crew','crop','crow','cube',
  'curb','curl','cute','dank','dare','dark','dart','dash','data','date','dawn',
  'dead','deaf','deal','dean','dear','deck','deed','deep','deer','demo','dent',
  'dill','dime','ding','disc','dish','disk','dive','dock','dote','dove','down',
  'drag','draw','drew','drip','drop','drum','dual','dull','dump','dung','dusk',
  'dust','dyne','each','earl','earn','easy','edge','emit','envy','even','ever',
  'exam','exit','fail','fair','fake','fall','fame','farm','fawn','feel','fell',
  'felt','fern','fife','fill','film','find','fine','fire','firm','fish','fist',
  'fizz','flak','flan','flat','flaw','flea','flee','flew','flex','flip','flop',
  'flow','foam','fold','folk','fond','food','fool','foot','ford','fork','form',
  'fort','foul','four','fowl','free','fret','frog','from','full','fume','fund',
  'fuse','gale','gall','game','gang','gate','gave','gaze','gear','geld','germ',
  'gift','gill','girl','give','glad','glob','glow','glum','gnaw','goal','goat',
  'gold','golf','gong','good','goof','gore','gout','grab','gray','grew','grin',
  'grip','grit','grog','groom','grow','grub','gulf','gull','gulp','gunk','gust',
  'hack','hail','hair','hale','half','hall','halt','hand','hang','hard','hare',
  'harp','hash','haul','have','hawk','haze','head','heal','heap','hear','heat',
  'heed','heel','heft','held','helm','help','hemp','herd','here','hero','high',
  'hill','hint','hire','hiss','hold','hole','home','hook','hoop','horn','hose',
  'host','hour','howl','hull','hump','hung','hunt','hurt','hymn','idle','inch',
  'iris','iron','isle','itch','jabs','jeer','jest','join','joke','jolt','jump',
  'just','keen','keep','kern','kill','kind','king','knew','knob','know','lack',
  'laid','lake','lamb','lame','lamp','land','lane','lard','lash','last','late',
  'laud','lead','leaf','leak','lean','leap','left','lend','lens','liar','lick',
  'lift','like','lime','limp','line','link','lion','list','live','load','loan',
  'lock','loft','lone','long','loon','loop','lord','lore','lorn','lour','lush',
  'lust','made','mail','main','make','male','mall','malt','many','mark','mars',
  'mast','mead','meal','mean','meat','meet','melt','menu','mere','mesh','mile',
  'milk','mill','mime','mind','mine','mint','miss','mist','moat','mode','monk',
  'moon','more','most','move','muck','mule','murk','must','mute','nail','name',
  'nary','neat','neck','need','news','next','nice','nine','node','none','noon',
  'nook','note','noun','nude','oath','obey','once','only','open','oral','oven',
  'over','page','pain','pair','pale','palm','pang','pave','peck','peel','peer',
  'pest','pick','pile','pine','ping','pink','pith','plan','play','plop','plot',
  'plow','ploy','plum','plus','poem','poet','pole','poll','pore','port','pose',
  'post','pour','pram','pray','prep','prey','prod','prop','pull','pump','pure',
  'push','quit','quiz','rack','ramp','rand','rang','rank','rant','reap','rely',
  'rest','rice','rich','ride','rife','rift','ring','riot','rise','risk','road',
  'roam','roar','robe','rock','rode','role','romp','roof','rope','rose','rout',
  'ruby','rude','rule','rump','rush','safe','sage','said','sail','sake','sale',
  'salt','same','sand','sang','sank','sash','save','seam','self','sell','send',
  'sent','sewn','shed','shin','ship','shoe','shot','show','shut','sick','side',
  'sigh','silk','sill','silo','sing','sink','size','skin','skip','slab','slag',
  'slap','slid','slim','slit','slow','slug','slum','snag','snap','snip','snob',
  'snub','soak','soar','sock','soft','soil','sold','some','song','soot','sore',
  'sort','soul','soup','sour','span','spar','spin','spit','spot','spun','spur',
  'stab','stag','star','stay','stem','step','stew','stir','stop','stub','stud',
  'stun','such','suit','sulk','surf','swam','swap','swat','swig','swim','swum',
  'tail','tale','tall','tame','tang','tank','tape','tart','task','taut','tear',
  'teem','tent','term','test','text','than','them','then','they','thin','this',
  'thus','tick','tile','till','time','tiny','tire','toad','tock','toff','tong',
  'took','tool','torn','toss','tour','town','tram','trap','tray','trek','trim',
  'trio','trip','trod','true','tube','tuck','tuft','turn','tusk','tutu','type',
  'ugly','unto','upon','urge','user','vary','veil','vein','very','vest','view',
  'visa','void','vote','wade','wage','wake','walk','wane','wart','wave','weak',
  'weal','weld','well','went','were','west','when','whet','whim','whin','whip',
  'whir','whit','whom','wide','wife','will','wilt','wine','wing','wink','wire',
  'wise','wish','with','woke','wolf','womb','wood','wool','word','wore','work',
  'worn','wren','writ','yawn','year','yell','your','zero','zest','zone','zoom',
  // 5-letter
  'abide','above','abuse','acted','acute','admit','adopt','adult','after','again',
  'agile','agree','ahead','aloft','alone','along','aloof','aloud','amber','amend',
  'among','ample','angel','angry','angst','annex','apart','apple','apply','aptly',
  'ardor','argue','arise','armed','arose','array','arrow','aside','asset','atlas',
  'atone','attic','audio','audit','avail','avoid','awake','award','aware','awful',
  'badly','baker','baron','basic','basis','batch','beach','began','begin','being',
  'below','bench','beset','black','blade','blank','blast','blaze','bleed','bless',
  'blind','block','blood','blown','board','bonus','boost','bound','brace','braid',
  'brain','brand','brave','bread','break','breed','brief','bring','broad','broke',
  'brood','brown','bruce','brunt','build','built','bulge','burnt','burst','cabin',
  'cache','caddy','cargo','carry','catch','cause','cease','chain','chalk','charm',
  'chase','cheap','check','cheek','cheer','chess','chest','chief','child','china',
  'choir','civic','civil','claim','clash','class','cleat','cleft','clerk','click',
  'cliff','cling','close','cloud','clout','clown','clump','coast','comet','comma',
  'coral','could','count','court','cover','crack','craft','cramp','crank','crash',
  'crawl','creak','creek','crisp','cross','crowd','crown','crush','crypt','cycle',
  'daily','dance','datum','dazed','dealt','death','decay','decoy','decry','defer',
  'delay','delta','demon','dense','depth','derby','devil','digit','dimly','dirty',
  'ditto','dizzy','dodge','doing','doubt','dough','dove','dowdy','draft','drain',
  'drank','dream','dress','drift','drive','drove','drown','druid','drunk','dryer',
  'eager','early','earth','edged','eight','elite','empty','ended','endow','enemy',
  'enjoy','enter','entry','equal','equip','error','essay','event','every','exact',
  'exist','extra','fable','faced','facet','faith','false','fancy','feast','fetch',
  'fever','fewer','fiber','field','fiery','fifty','fight','final','first','fixed',
  'flags','flame','flank','flair','flaw','flesh','flint','float','flood','floor',
  'flour','flown','focus','forge','found','frame','frank','fraud','fresh','front',
  'froze','fruit','fully','funky','funny','ghost','giant','given','gland','glare',
  'glass','gleam','glide','gloat','globe','gloom','gloss','glove','going','grace',
  'grade','grain','grand','grant','grape','grasp','grass','great','greed','green',
  'greet','grief','grime','grind','groan','groin','grope','gross','group','growl',
  'gruel','gruff','guard','guess','guide','guild','guile','guise','gulch','harsh',
  'haste','hatch','haunt','haven','heart','heavy','hedge','hence','herbs','hinge',
  'hobby','honor','horse','hotel','hovel','human','humor','husky','ideal','image',
  'imply','infer','ingot','input','inter','inure','issue','ivory','jaunt','jewel',
  'judge','juice','jumpy','juror','knack','kneel','knife','knock','known','label',
  'lance','large','laser','later','laugh','layer','layup','learn','least','legal',
  'level','light','limit','linen','liver','local','lodge','logic','loose','lover',
  'lower','loyal','lucky','lusty','magic','major','maker','march','match','mayor',
  'mercy','merit','melee','metal','might','minor','minus','model','month','moral',
  'mourn','mount','mouse','mouth','mover','moved','muddy','music','naive','nasty',
  'naval','nerve','never','night','noble','noise','north','noted','novel','nurse',
  'ocean','offer','often','olive','onset','other','ought','ounce','outer','oxide',
  'ozone','oxide','pagan','paint','panel','paper','party','pasta','patch','pause',
  'peace','pearl','pedal','penny','phase','phone','photo','piano','pinch','pixel',
  'pivot','pizza','plain','plane','plant','plate','plaza','plead','pluck','plume',
  'plunk','point','poise','polar','porch','pound','power','press','price','pride',
  'prime','print','prism','privy','probe','prone','proof','proud','prove','psalm',
  'pulse','punch','queen','query','queue','quiet','quite','quota','quote','radar',
  'radio','raise','range','rapid','ratio','reach','react','ready','realm','rebel',
  'refer','refit','reign','relax','renew','repay','repel','reply','rider','ridge',
  'right','rigid','risky','rival','rivet','rogue','roman','roost','round','royal',
  'rugged','ruins','rural','rusty','salve','scald','scalp','scant','scare','scene',
  'scorn','scout','scowl','scrap','screw','scrub','seize','sense','serve','seven',
  'shade','shaft','shake','shall','shame','shape','sharp','sheen','sheep','sheer',
  'shelf','shift','shine','shirt','shore','short','shout','shove','skill','skirt',
  'skull','slain','slant','slave','sleek','sleep','sleet','slice','slime','slink',
  'slope','sloth','slump','slunk','slurp','smart','smash','smear','smile','smoke',
  'snail','snake','snare','sneak','sniff','snore','solar','solid','solve','sorry',
  'sound','south','space','spare','speak','spear','speck','speed','spend','spent',
  'spice','spike','spine','spite','split','spoke','spook','spore','sport','spray',
  'sprig','squad','squat','squid','staff','stain','stake','stale','stall','stamp',
  'stand','stark','start','state','stave','steal','steam','steel','steer','stick',
  'sting','stock','stomp','stone','stood','store','storm','stout','stove','strap',
  'stray','strip','strive','study','stuff','stump','swamp','swear','sweep','swept',
  'swift','swing','swore','sword','table','taste','teach','tears','thank','theme',
  'thick','thing','think','thorn','those','three','threw','throe','throw','thumb',
  'tiger','timed','tired','title','toast','today','token','total','touch','tough',
  'trace','track','trade','trail','train','trait','trash','treat','tree','trend',
  'trial','tribe','trick','tried','troop','trove','truck','truly','trump','trunk',
  'trust','truth','tumor','tuner','twain','tweak','twice','twist','tying','ultra',
  'uncle','under','unify','union','unite','unity','until','upset','usage','usual',
  'utter','vague','valid','valor','value','vapor','vault','veins','verse','vigor',
  'viral','virus','visit','vital','vivid','vocal','voice','vouch','wager','waste',
  'watch','water','weave','weedy','weigh','weird','whale','wheat','wheel','where',
  'while','whirl','white','whole','whose','wider','width','wield','witty','woman',
  'women','world','worry','worse','worst','worth','wound','wrath','write','wrote',
  'yacht','yield','young','youth','zesty',
  // 6-letter
  'absent','absorb','abrupt','accent','accept','access','accord','accuse','achieve',
  'across','actual','adjust','admire','affect','afford','agency','agents','almost',
  'always','ambush','amount','animal','answer','anyone','appeal','appear','assign',
  'assist','assume','attack','author','autumn','awaken','barely','battle','become',
  'before','behind','belong','beyond','bridge','bright','broken','brutal','buried',
  'button','cached','cannot','castle','change','charge','choice','choose','chosen',
  'church','circle','citing','client','clouds','colour','combat','common','copper',
  'corner','cotton','county','course','courts','create','credit','crisis','danger',
  'debate','decide','defend','define','degree','design','desire','detail','detect',
  'devise','direct','divide','dollar','domain','double','driven','during','effect',
  'effort','eighth','either','eleven','empire','enable','energy','engage','enough',
  'ensure','entire','escape','except','expand','expect','export','extend','fabric',
  'factor','fallen','family','famous','father','figure','finger','fished','follow',
  'forest','forget','formal','friend','future','garden','gather','global','glance',
  'golden','govern','ground','growth','happen','hardly','hatred','health','hidden',
  'higher','honest','ignore','impact','import','income','indeed','injury','inside',
  'insist','invest','island','itself','jungle','junior','keeper','knight','ladder',
  'lancer','latest','lawful','leader','league','length','lesson','letter','listen',
  'living','longer','lowest','method','middle','mirror','missed','modern','moment',
  'monkey','motion','muscle','mutual','narrow','nation','nature','nearby','needle',
  'normal','notice','notion','number','object','obtain','office','online','oppose',
  'option','orient','origin','output','palace','parent','people','period','permit',
  'phrase','player','plunge','police','policy','poison','portal','prefer','pretty',
  'prince','prison','profit','proper','public','pursue','puzzle','rather','really',
  'reason','recent','regard','region','relate','remain','remove','render','repeat',
  'report','result','return','reveal','review','revive','reward','rhythm','rising',
  'robust','rotate','rough','rounds','rubber','ruling','runner','sacred','safety',
  'sample','school','search','second','secret','select','series','simple','single',
  'sister','skills','slowly','source','spirit','stable','starts','stated','status',
  'strain','stream','street','stress','strict','strong','struck','stupid','submit',
  'suburb','summer','supply','surely','system','talked','target','terror','thanks',
  'theory','though','threaten','toward','travel','tunnel','twenty','unfair','unique',
  'unlike','useful','valley','varies','versus','victim','vision','volume','unless',
  'wealth','weekly','weight','within','wonder','wooden','worker','worlds','worthy',
  'writer','yellow','zipper',
  // 7-letter
  'absence','account','achieve','acquire','address','advance','against','already',
  'ancient','another','anxiety','anybody','arrange','arrival','assault','attempt',
  'average','balance','believe','benefit','between','binding','captain','capture',
  'century','certain','chapter','charity','circuit','citizen','clearly','climate',
  'collect','combine','command','comment','complex','concept','concern','conduct',
  'confirm','connect','contain','control','council','country','courage','current',
  'custody','cutting','dealing','decided','declare','defense','deliver','density',
  'deposit','develop','diamond','digital','disable','disease','dismiss','display',
  'dispute','distant','divided','dollars','dominate','dynasty','eastern','economy',
  'element','emotion','endless','enforce','enhance','failure','feature','finance',
  'finding','forward','fulfill','general','genuine','greatly','habitat','harvest',
  'healing','healthy','history','horizon','however','hundred','husband','imagine',
  'improve','include','initial','inquiry','inspire','instead','journey','justice',
  'kingdom','knowing','lacking','leading','library','literal','magical','maximum',
  'measure','meeting','message','million','mineral','mission','mixture','monitor',
  'morning','natural','network','nothing','nuclear','obvious','organic','outcome',
  'package','pattern','perform','perhaps','picture','popular','present','prevent',
  'produce','program','protect','purpose','qualify','quality','quickly','recover',
  'require','resolve','restore','retreat','revenue','rotting','session','setting',
  'service','shelter','silence','similar','society','soldier','species','sorcery',
  'strange','succeed','suggest','support','surface','survive','teacher','through',
  'tonight','totally','trading','trouble','turning','typical','unified','unknown',
  'usually','village','violent','warrior','weather','western','whether','without',
  'working','writing',
  // 8-letter
  'absolute','abstract','accepted','accident','accurate','achieved','actually',
  'addition','adequate','adjacent','advanced','affected','alliance','allowing',
  'alphabet','although','analysis','ancestor','animated','announce','apparent',
  'appetite','argument','assembly','assigned','attached','attract','balanced',
  'baseline','beautifully','becoming','behavior','blessing','boundary','breaking',
  'campaign','capacity','carrying','catching','ceremony','champion','changing',
  'character','children','clearing','climbing','collapse','combined','complete',
  'conceive','conflict','consider','constant','consumed','continue','contrary',
  'convince','creating','creature','criteria','cultural','darkness','decision',
  'declared','defeated','defining','describe','detailed','devoting','diamond',
  'directly','disaster','distract','division','dominant','downfall','dreaming',
  'duration','dwelling','enjoying','enormous','entirely','entrance','equality',
  'evaluate','evidence','evolving','existing','explode','explored','exposure',
  'external','familiar','fighting','finished','flexible','flashing','floating',
  'focusing','followed','forecast','forestall','forgiven','fraction','fragment',
  'freezing','frontier','function','generate','guardian','guidance','happened',
  'heritage','horrible','hospital','identify','imagined','immortal','impacted',
  'improved','increase','indicate','inherent','innocent','isolated','judgment',
  'language','learning','location','maintain','manifest','material','maximize',
  'medicine','minister','moderate','momentum','movement','multiple','negative',
  'newcomer','northern','notional','observed','operated','overcome','position',
  'powerful','practice','previous','princess','probable','progress','property',
  'proposal','protocol','provided','pursuing','question','received','recovery',
  'register','regulate','rejected','relation','reliable','required','research',
  'reserved','resource','response','resulted','revision','rightful','rotation',
  'sacrifice','scenario','schedule','security','sensible','sequence','services',
  'shifting','shoulder','singular','skeleton','sleeping','solution','somebody',
  'somewhat','southern','speaking','specific','standard','standing','starting',
  'strategy','strength','struggle','stunning','subjects','surprise','survival',
  'symbolic','targeted','together','tomorrow','transfer','traveled','treasury',
  'ultimate','uncommon','underway','universe','unlikely','variable','versed',
  'volcanic','watching','whatever','whenever','wherever','yourself',
  // ── Supplemental common words (fill gaps players naturally hit) ──────────
  // -AZE / -AZY / -AZZ
  'daze','gaze','haze','laze','maze','raze','adze','jazz','fizz','fuzz','buzz',
  'lazy','hazy','cozy','dozy','oozy','waxy','sexy','foxy','boxy','rosy','nosy',
  'posy','rosy','cosy','easy','espy',
  // -OLE family
  'dole','mole','role','sole','vole','pole','bole','knoll','scroll','stroll',
  'toll','doll','poll','roll','loll','coll','folly','jolly','molly','dolly',
  // -OLD family
  'bold','cold','fold','gold','hold','mold','sold','told','wold',
  'scold','behold',
  // -ALD / -ALK / -ALL family
  'bald','walk','talk','chalk','stalk','hall','ball','call','fall','gall',
  'hall','mall','pall','tall','wall','yall','small','shall',
  // -ULD / -ULL / -ULK
  'bulk','hulk','sulk','skull','dull','full','gull','hull','lull','mull','null',
  'pull','bull','cull',
  // -UB / -UG / -UM extras
  'club','drub','flub','grub','slub','snub','scrub','shrub','stub','rub',
  'slug','drug','plug','shug','snug','smug','chug','thug','lug','bug',
  'drum','plum','slum','scum','stum','glum','gum','hum','rum','sum',
  // -AD / -AG / -AB extras
  'glad','clad','brad','grad','scad','shad','quad',
  'brag','crag','drag','flag','frag','snag','stag','swag','shag',
  'crab','drab','grab','scab','slab','stab',
  // -AN / -AM / -AP extras
  'bran','clan','plan','scan','span','than','tran',
  'clam','cram','dram','gram','pram','sham','slam','swam','tram','yam',
  'clap','crap','flap','knap','slap','snap','strap','trap','wrap',
  // -AY / -AIT / -AKE / -ANE extras
  'bray','clay','dray','flay','fray','gray','play','pray','slay','sway','tray',
  'waif','wait','bait','fait','gait','malt','salt','halt',
  'bake','cake','fake','lake','make','rake','sake','take','wake','brake',
  'crane','cane','lane','mane','pane','sane','vane','wane','bane','jane',
  // -EAK / -EAL / -EAM / -EAP / -EAR / -EAT extras
  'beak','freak','leak','peak','sneak','speak','teak','weak','creak',
  'deal','feel','heel','keel','kneel','meal','peel','real','seal','teal','veal',
  'beam','cream','dream','gleam','ream','scream','seam','steam','team',
  'heap','leap','reap',
  'fear','gear','hear','lear','near','pear','rear','sear','tear','wear','year',
  'feat','heat','meat','neat','peat','seat','teat','beat','cheat','pleat','wheat',
  // -ICK / -ILL / -IMP / -ING / -INK / -INT / -ISH / -ISK / -IST / -ITC
  'brick','click','flick','prick','quick','slick','stick','thick','trick','wick',
  'bill','fill','gill','hill','kill','mill','pill','sill','spill','still','till',
  'blimp','chimp','crimp','primp','skimp','wimp',
  'bring','cling','fling','king','ring','sling','spring','sting','string','swing','thing',
  'blink','brink','clink','drink','link','mink','pink','rink','sink','stink','wink',
  'flint','glint','hint','mint','print','sprint','squint','stint','tint',
  'dish','fish','wish','swish',
  'disk','brisk','risk','whisk',
  'fist','gist','grist','list','mist','twist','wrist',
  // -OAK / -OAM / -OAN / -OAR / -OAT extras
  'cloak','croak','soak',
  'foam','loam','roam',
  'groan','loan','moan','groan',
  'roar','boar',
  'bloat','coat','float','gloat','goat','moat','throat',
  // -OCK / -OG / -OID / -OIL / -OIN / -OKE / -ONG / -OOK / -OOM / -OON / -OOP / -OOT
  'block','clock','dock','flock','frock','knock','lock','mock','rock','shock','sock','stock',
  'blog','clog','flog','slog','smog',
  'avoid','void',
  'broil','coil','foil','moil','soil','toil',
  'coin','groin','join','loin',
  'bloke','broke','cloak','cloke','coke','folk','poke','smoke','spoke','stoke','woke','yoke',
  'bong','dong','gong','prong','song','strong','tong','throng','wrong',
  'book','brook','cook','crook','hook','look','nook','rook','shook','took',
  'bloom','broom','doom','gloom','groom','loom','room','zoom',
  'boon','croon','goon','loon','moon','noon','soon','spoon','swoon','toon',
  'droop','hoop','loop','poop','scoop','sloop','snoop','stoop','swoop','troop',
  'boot','hoot','loot','moot','root','scoot','shoot','soot','toot',
  // -UCK / -UG / -UMP / -UNG / -UNK / -UNT / -USH / -UST extras
  'buck','chuck','cluck','duck','luck','muck','pluck','puck','stuck','suck','tuck',
  'lung','rung','sung','stung','swung','wrung','young',
  'bump','clump','dump','frump','grump','hump','jump','lump','plump','pump','rump','slump','stump','trump',
  'bunk','chunk','clunk','drunk','dunk','funk','gunk','hunk','junk','punk','skunk','slunk','spunk','stunk','sunk','trunk',
  'blunt','bunt','front','grunt','hunt','punt','runt','shunt','stunt',
  'blush','brush','crush','flush','gush','hush','lush','mush','plush','rush','slush',
  'bust','dust','gust','just','lust','must','rust','thrust','trust',
  // -EEN / -EEP / -EER / -EES / -EET / -EEZ
  'been','keen','preen','queen','screen','seen','spleen','teen','between',
  'beep','cheep','creep','deep','jeep','keep','peep','seep','sheep','sleep','steep','sweep','weep',
  'beer','cheer','deer','jeer','leer','peer','sheer','sneer','steer',
  'beet','feet','fleet','greet','meet','sheet','sleet','street','sweet',
  // Adjectives / misc common
  'able','aged','akin','aloe','anew','apex','arch','avid','awed','awry',
  'boon','bore','bred','brig','bulk','cede','clue','clad','coup','coif',
  'dame','dato','deft','dell','demi','deny','dire','dote','dove','drab',
  'dull','dupe','each','edgy','eely','eked','elan','else','epic','even',
  'evil','exam','exert','expo','fare','feat','fiat','fife','folk','fond',
  'fore','fort','four','fowl','free','fume','gait','gamy','gape','garb',
  'gave','geld','gibe','gist','glut','gone','gore','gory','gout','grit',
  'hale','hard','harm','harp','have','hawk','haze','hemp','hers','hest',
  'hive','hoar','hone','hope','hurl','idle','imps','inky','isle','itch',
  'jaunt','jibe','jive','jolt','keen','kink','knit','kyat','lame','laud',
  'laze','lean','left','lend','levy','lewd','lieu','lilt','lisp','lithe',
  'lore','lout','lure','lush','lust','lyfe','mace','male','malt','mane',
  'many','mare','mark','mass','mate','maul','mean','meet','meek','mere',
  'mesh','mice','mild','mime','mine','mint','mire','mise','mitt','mode',
  'more','mote','moue','much','muse','musk','nail','nave','near','neat',
  'newt','nice','nimb','node','nome','noon','nose','nude','null','oboe',
  'once','ooze','oral','orb','ours','pact','page','pair','pale','pare',
  'pave','pawl','peak','peat','peel','pelf','pend','pent','pile','pimp',
  'pipe','pita','pity','plan','plea','plop','plot','ploy','plum','plus',
  'poem','poke','pond','pont','pose','post','pour','prey','prob','prod',
  'prof','prop','pulp','pure','pyre','rapt','raze','reef','rein','rely',
  'rend','rent','rest','rift','rill','rime','rind','riot','ripe','rite',
  'rive','rode','rook','rove','ruin','ruse','rust','ryes','safe','sake',
  'same','sane','save','seam','sere','shed','shin','shot','show','shun',
  'simp','size','slat','slim','slip','slot','slur','soak','soar','sole',
  'some','sore','sort','soul','span','spit','spot','stab','stag','star',
  'stat','stem','stew','stir','stop','stub','stud','sway','sync','syrup',
  'tabs','tail','tale','tall','tame','tare','taut','temp','tend','test',
  'thin','tiff','till','tithe','tome','tone','took','tore','toss','tour',
  'town','trod','true','tuft','turf','tuft','type','ugly','unto','upon',
  'urge','vain','vale','vane','vary','veer','veil','verb','vice','vile',
  'vine','vise','void','vote','wade','waft','wage','wake','wane','wart',
  'weal','weld','when','whet','whim','whin','whit','wick','wile','wimp',
  'wine','wink','wire','wise','woke','womb','wood','wool','worn','wove',
  'wren','writ','yawn','yell','zero','zest','zinc','zone','zoom',
  // ── Extended dictionary (additional ~4 000+ words) ─────────────────────────
  // 3-letter additions
  'bee','cob','cue','due','duo','gem','hen','lob','lox','sec','sue','ton','tot',
  'vex','vie','yep','phi','chi','tau','thy','tic','ohm','goo','orc','beg','cod',
  'cog','fez','jot','lei','nee','oho','qua','ram','roe','rue','taw','uke','zap',
  'amp','asp','aye','bub','bum','caw','cel','che','dab','deh','dex','efs','els',
  'ems','ens','eon','ers','eta','feh','hep','het','hob','hoe','hoo','ick','ins',
  'ken','kir','kop','lea','mob','moo','nab','nae','nip','nit','nob','obe','obi',
  'oda','oke','ole','oms','ops','ors','oud','ova','pah','pes','pip','poh','poi',
  'pol','pom','pow','raj','rec','rep','ret','rev','roe','rho','sec','sei','ser',
  'sha','sib','sin','sod','sol','sou','soy','spa','spy','sty','sue','sup','tab',
  'taj','tav','tew','thy','tod','tog','tui','ulu','uns','upo','urd','vav','vaw',
  'vex','wab','wog','wop','wos','wow','xis','yah','yid','yob','yod','yow','zag',
  'zax','zed','zig','zit',
  // 4-letter additions
  'abut','acme','acne','ahoy','akin','aloe','amen','amok','anew','ante','anti',
  'apex','arty','atop','axle','bail','bait','balm','bath','bawl','beau','beet',
  'bile','bind','blob','bloc','bode','boon','boor','born','brow','buff','bulb',
  'burl','chap','char','chew','chop','clog','cope','cuss','dale','daze','drab',
  'drat','echo','epic','flay','flit','flue','funk','fury','gash','glut','gory',
  'hewn','hike','hilt','inky','jibe','jinn','lark','laze','lurk','lynx','miff',
  'molt','ogre','pact','pall','rave','rein','rend','rent','reek','skim','skit',
  'slat','slew','sloe','smug','snot','sown','spry','tack','teen','tend','thud',
  'vale','vane','veal','verb','vile','vise','wail','ware','wary','wasp','wick',
  'yoke','yore','bole','cede','clue','coup','dame','deft','demi','dire','dupe',
  'edgy','elan','evil','fare','fiat','fore','gait','gamy','gape','garb','gibe',
  'gist','harm','hest','hive','hoar','hone','hurl','jive','kink','knit','laud',
  'lewd','lieu','lilt','lisp','lore','lout','lure','mace','mare','mass','mate',
  'maul','meek','mice','mild','mire','mitt','mote','moue','muse','musk','nave',
  'newt','null','oboe','ooze','pare','pawl','peat','pelf','pend','pent','pimp',
  'pipe','pity','plea','ploy','pond','pulp','pyre','rapt','raze','reef','rime',
  'rind','ripe','rite','rive','rook','rove','ruin','ruse','sere','shun','simp',
  'slur','sole','stat','sway','tabs','temp','tome','tone','tore','turf','vain',
  'veer','vice','vine','waft','wile','wimp','wove','brig','dame','dint','doit',
  'dojo','dong','dory','doss','dote','dots','dour','doze','drab','dreg','drip',
  'drib','droit','drub','drum','duel','duke','dulce','dun','duos','dusk','dyke',
  'echt','eire','eke','ekes','elan','elms','endue','epee','eses','esse','espy',
  'etna','euro','ever','evoe','exec','expo','fain','fane','fash','faze','fees',
  'fell','fems','fens','feud','fief','fink','flag','flam','flat','flaw','flay',
  'flea','flew','flex','flit','floe','flux','foal','fobs','fohn','fond','fops',
  'forb','fore','form','froe','from','fuze','gaen','gals','gamb','gash','gasp',
  'gawk','gean','gee','geek','ghee','glee','glop','glow','gnar','gnaw','gobs',
  'goes','gore','govs','gowd','gowk','gowl','grab','grad','gram','gray','grrl',
  'guck','gude','guff','guhn','gulp','hack','hags','hale','halt','hame','hams',
  'haps','hasp','hazy','heed','hemp','herd','hewn','hies','hilt','hire','hiss',
  'hobo','hobs','hods','hoik','honk','hoop','hora','hose','hots','howl','huia',
  'hunk','hurt','hymn','ibis','idea','idle','ileum','imam','impi','inch','indy',
  'inro','ions','iota','ires','irks','isle','isms','isnt','iter','jabs','jade',
  'jasp','jato','jell','jibe','jinx','jism','jive','juga','junk','jura','kale',
  'kart','kats','keck','kerf','kern','khat','khis','kick','kike','kilt','kipper',
  'kirs','kith','knap','knur','koel','kola','koph','lade','lahs','lakh','lams',
  'lamp','lari','lark','lath','lave','laze','leam','lede','lehr','leno','lens',
  'levy','lewd','libs','lick','lido','lier','lima','limp','linc','lino','lira',
  'lore','lorn','lour','lout','lude','lune','lung','lunk','lure','lynx','lyse',
  'maar','mabe','mace','mads','maes','mage','mags','maid','maim','malt','mama',
  'mana','manx','mare','marge','masu','maze','mead','mesa','mete','mibs','mien',
  'mill','mime','mirk','mise','mitt','moat','mobs','mock','mojo','mols','molt',
  'mome','monk','mope','mora','mote','moue','mown','mozo','much','muff',
  'mugg','mump','murk','muse','mute','myah','narc','nark','nave','neem','nerd',
  'newt','nibs','nils','nips','nobs','node','nome','nong','nonk','nook','norm',
  'nota','nude','nuke','numb','nyah','oboe','odds','ohms','oleo','olio','omit',
  'onyx','orbs','orca','otic','otto','ouph','ovum','oxen','paca','pace','pacs',
  'pacy','pads','page','pain','pak','pander','pard','pare','park','pash','paws',
  'peat','peds','peke','pele','pell','pelts','pend','pens','pepo','perp','phon',
  'phat','phut','pice','pier','pile','piny','pixy','pleb','plod','plop','ploy',
  'plum','plus','poem','pogy','pois','poke','pole','poly','pome','pood','port',
  'posh','pout','pows','pram','prau','pree','prey','proa','prof','prog','puke',
  'pulp','puma','punk','pure','purr','push','putz','quay','quid','rads','rale',
  'rami','rand','rang','rats','rave','rays','raze','razz','read','reek','rein',
  'rend','rent','repo','resh','rhos','ribs','rice','rich','rick','riff','rime',
  'rimy','rins','riot','risk','road','roam','roil','rolf','rook','rort','rove',
  'rube','rude','ruin','rune','rusa','rush','ryot','safe','sage','said',
  'sail','sake','saki','salt','salp','same','sand','sang','sank','sash','save',
  'seam','sear','sect','self','sell','sent','sewn','shag','shan','shed','shin',
  'shiv','shoe','shot','show','shut','sial','sick','side','sigh','silk','sill',
  'silo','sing','sink','size','skin','skip','slab','slap','slid','slim','slit',
  'slog','slow','slug','slum','snag','snap','snip','snob','snub','soak','soar',
  'sock','soft','soil','sold','some','song','soot','sore','sort','soul','soup',
  'sour','spae','span','spar','spin','spit','spot','spun','spur','stab','stag',
  'star','stay','stem','step','stew','stir','stop','stub','stud','stun','such',
  'suit','sulk','sump','surf','swam','swap','swat','swig','swim','swum','tace',
  'tach','tail','tale','tall','tame','tang','tank','tape','tare','tart','task',
  'taut','tear','teem','teff','tent','term','test','text','than','them','then',
  'thin','this','thus','tick','tile','till','time','tiny','tire','toad','tock',
  'toft','togs','tong','took','tool','torn','tors','toss','tout','town','tram',
  'trap','tray','trek','trim','trio','trip','trod','true','tube','tuck','tuft',
  'turn','tusk','ugly','unto','upon','urge','user','vary','veil','vein','very',
  'vest','view','visa','void','vote','wade','wage','wake','walk','wane','wart',
  'wave','weak','weal','weld','went','were','west','when','whet','whim','whin',
  'whip','whit','whom','wide','wife','will','wilt','wine','wing','wink','wire',
  'wise','wish','wolf','womb','wood','wool','word','wore','work','worn',
  // 5-letter additions
  'abhor','abode','abort','abuzz','acorn','adage','adept','adore','adorn','aegis',
  'afoul','agave','aglow','agony','agora','ahold','ahull','aided','aimer','aisle',
  'alarm','album','algae','alibi','align','alike','allay','alley','allow','aloft',
  'alter','amaze','amble','amend','amiss','amply','ample','amuse','annoy','anvil',
  'apron','ardor','aroma','arson','artsy','ascot','ashen','askew','atoll','attic',
  'audio','augur','avert','awash','awoke','azure','badge','badly','bandy','banjo',
  'baron','baste','began','belch','belie','beset','bevel','bigot','bilge','bingo',
  'biome','birch','bland','blare','bleat','blimp','blunt','bolts','botch','boxer',
  'brash','brink','brisk','brine','broil','broth','burly','bushy','bustle','butch',
  'cache','camel','cameo','candy','canny','canon','carat','cargo','carol','caste',
  'cedar','chore','chunk','civic','civil','clank','clasp','cleft','clung','cobra',
  'cocoa','comet','couch','cough','coupe','covet','craft','cramp','crave','crawl',
  'creak','creed','crest','croup','crude','crumb','crush','cutie','decal','decoy',
  'delve','depot','deter','ditty','divvy','dodge','dowdy','dowry','draft','drape',
  'drawl','drool','dross','dunce','dusky','dusty','dwarf','dwell','edict','ensue',
  'epoxy','epoch','equip','evade','evoke','fable','faint','farce','fatal','feral',
  'finch','fizzy','fjord','flair','flare','flesh','flint','flora','floss','fluky',
  'flunk','flute','folly','forgo','forte','foyer','frail','freak','frisk','froze',
  'gaunt','gauze','gawky','genre','germs','gimpy','gizmo','glaze','gleam','glint',
  'gloss','gnash','gnome','graft','gravy','graze','grill','gripe','groan','groin',
  'grope','gross','grove','gruel','guile','gusto','gutsy','hammy','handy','hardy',
  'haste','haven','hazel','heady','heave','hedge','heist','hence','herby','hippy',
  'hoary','homer','hooky','horny','hotly','hovel','humid','hunch','hunky','icing',
  'iffy','image','imply','infer','ingot','inter','ionic','irate','jaunt','jazzy',
  'jewel','jiffy','juicy','jumpy','knave','kneel','knell','knelt','knoll','kudos',
  'lanky','lapel','lapse','larva','latch','lathe','leaky','leapt','ledge','leech',
  'lefty','lemma','liege','liner','lithe','liven','llama','lobby','loopy','lorry',
  'lousy','lucid','lucky','macho','maize','manga','manly','manor','maple','mealy',
  'melon','merry','messy','might','minty','moody','mossy','moxie','moose','muddy',
  'muggy','mulch','murky','mushy','musty','navel','nifty','ninja','nippy','nitro',
  'oaken','ochre','optic','otter','ovary','ozone','pansy','pasty','patsy','perky',
  'pesky','petty','phony','pilot','plaid','plank','plaza','plead','plunk','podgy',
  'polyp','poppy','porky','posit','potty','privy','prude','prune','pubic','pulpy',
  'punchy','purse','quaff','quail','quake','qualm','quart','quasi','quilt','rainy',
  'randy','raven','rangy','reedy','refit','relay','repay','repel','rider','ridge',
  'rinky','rivet','rover','rowan','rummy','rusty','sadly','salty','sassy','savvy',
  'scald','scalp','scant','scare','scone','scoop','scoot','scorn','scout','scowl',
  'scram','sedan','seedy','seize','shady','shaky','shiny','shire','sieve','sinew',
  'skimp','skulk','slang','slant','sleek','slung','slyly','snack','snaky','snide',
  'snoop','snort','snowy','soggy','sonny','soppy','spade','spawn','spill','spire',
  'splat','spoof','spout','stiff','stilt','stomp','stood','straw','stump','suave',
  'suite','sulky','sunny','surly','swoop','tacky','tango','tardy','tarry','tasty',
  'tatty','taunt','tawny','tempt','tepid','tight','tipsy','token','torso','touchy',
  'tramp','trite','troth','tubby','tyke','ulcer','uncut','usher','vaunt','vapid',
  'venal','vigil','viper','waken','wanna','warty','weedy','whack','wimpy','wooly',
  'wormy','would','wrapt','wreck','wring','yeoman','yokel','zappy','zippy','zombie',
  'abode','agile','algae','amble','aping','arced','ashed','attic','axing','baled',
  'baser','batch','bated','being','bison','biter','bliss','bloat','blobs','blogs',
  'blown','bluer','boats','bonds','boney','boxer','brood','brook','brunt','buddy',
  'bugle','burns','burps','buyer','cafes','caged','capes','caped','cares','cased',
  'cedar','chaos','chide','chink','choir','chose','cited','cites','civic','civil',
  'claim','class','clean','clear','climb','clock','clone','close','cloud','clown',
  'coded','comet','comic','coral','cores','coups','cozy','crags','crams',
  'crane','crate','crave','cream','creds','crept','cried','crimp','crown','cubic',
  'curls','curve','cushy','daffy','dairy','dated','debut','decry','delta','demon',
  'dense','derby','doing','dowel','drags','drily','drove','dryer','duchy','dumpy',
  'eager','early','edged','eight','empty','ended','enter','entry','equal','event',
  'every','exact','exist','extra','faced','faith','falls','false','fated','faze',
  'fewer','fiery','fifty','first','fixed','flame','flank','flesh','flint','float',
  'flood','floor','flour','flown','focus','forge','found','frame','frank','fraud',
  'fresh','front','fruit','fully','funky','funny','ghost','giant','given','gland',
  'glare','glass','glide','gloat','globe','gloom','gloss','glove','going','grace',
  'grade','grain','grand','grant','grape','grasp','grass','great','greed','green',
  'greet','grief','grime','grind','group','growl','guard','guess','guide','guild',
  'gulch','harsh','hatch','haunt','heart','heavy','hence','herbs','hinge','hobby',
  'honor','horse','hotel','human','humor','husky','ideal','image','imply','infer',
  'ingot','input','inter','inure','issue','ivory','judge','juice','jumpy','juror',
  'knack','knife','knock','known','large','laser','later','laugh','layer','learn',
  'least','level','light','limit','linen','liver','local','lodge','logic','loose',
  'lower','loyal','lucky','lusty','magic','major','maker','match','mercy','merit',
  'metal','minor','minus','model','month','moral','mourn','mount','mouse','mouth',
  'moved','muddy','music','naive','nasty','naval','nerve','night','noise','north',
  'novel','nurse','offer','often','onset','other','outer','oxide','pagan','paint',
  'panel','paper','party','pasta','patch','pause','peace','pearl','pedal','penny',
  'phase','phone','photo','piano','pinch','pixel','pivot','pizza','plain','plane',
  'plant','plate','pluck','plume','plunk','point','poise','polar','porch','pound',
  'power','press','price','pride','prime','print','prism','probe','prone','proof',
  'proud','prove','psalm','pulse','punch','queen','query','queue','quiet','quite',
  'quota','radar','radio','raise','range','rapid','ratio','reach','react','ready',
  'realm','rebel','refer','reign','relax','renew','repay','repel','reply','right',
  'rigid','risky','rival','rivet','rogue','roost','round','royal','ruins','rural',
  'salve','scene','scrap','screw','scrub','sense','serve','seven','shade','shaft',
  'shake','shall','shame','shape','sharp','sheen','sheep','sheer','shelf','shift',
  'shine','shirt','shore','short','shout','shove','skill','skirt','skull','slain',
  'slave','sleek','sleep','sleet','slice','slime','slink','slope','sloth','slump',
  'slunk','slurp','smart','smash','smear','smile','smoke','snail','snake','snare',
  'sneak','sniff','snore','solar','solid','solve','sorry','sound','south','spare',
  'speak','spear','speck','speed','spend','spent','spice','spike','spine','spite',
  'split','spoke','spook','spore','sport','spray','sprig','squad','squat','squid',
  'staff','stain','stake','stale','stall','stamp','stand','stark','start','state',
  'stave','steal','steam','steel','steer','stick','sting','stock','stomp','stone',
  'store','storm','stout','stove','strap','stray','strip','study','stuff','swamp',
  'swear','sweep','swept','swift','swing','swore','table','taste','teach','tears',
  'thank','theme','thick','thing','think','thorn','those','threw','throe','throw',
  'thumb','tiger','tired','title','toast','today','total','touch','tough','trace',
  'track','trade','trail','train','trait','trash','treat','trend','trial','tribe',
  'trick','tried','troop','trove','truck','truly','trump','trunk','trust','truth',
  'tumor','tuner','twain','tweak','twice','twist','ultra','uncle','unify','union',
  'unite','unity','until','upset','usage','usual','utter','vague','valid','valor',
  'value','vapor','vault','verse','vigor','viral','virus','visit','vital','vivid',
  'vocal','voice','vouch','wager','waste','watch','water','weave','weedy','weigh',
  'weird','whale','wheat','wheel','where','while','whirl','white','whole','whose',
  'wider','width','wield','witty','woman','women','world','worry','worse','worst',
  'worth','wound','write','wrote','yacht','yield','young','youth','zesty',
  // 6-letter additions
  'ablaze','abound','abroad','absorb','absurd','accrue','aceite','aching','acting',
  'active','actual','adhere','adjoin','admire','adrift','advent','adverb','aerial',
  'affirm','afford','afloat','afraid','aghast','alight','allege','allied','allure',
  'almost','altars','ambush','amends','amiable','amount','ample','analog','annals',
  'annual','anyway','aplenty','appall','arouse','artist','ascend','aspire','assail',
  'assets','astray','atrium','attest','attire','auburn','author','avenue','avenge',
  'avocado','awning','banter','barley','barrel','barons','batter','befall','bellow',
  'beware','bicker','bitter','blouse','blower','blurry','bodily','bolted','bonded',
  'botany','bounty','breach','breezy','breton','bribed','bridle','broker','browse',
  'bruise','bundle','bungle','burrow','bustling','byline','candor','career','castle',
  'casual','catchy','cavern','cement','chalet','chorus','citrus','clamor','classy',
  'cliche','clings','coarse','cobalt','cobble','codify','colony','combat','comply',
  'compel','cooler','costly','couple','coupon','cramped','crafty','crater','crazed',
  'credit','creepy','crimson','crisply','critic','crumble','crunch','cubicle','curled',
  'curly','custom','cyborg','cynical','dagger','dainty','dampen','dawdle','dawning',
  'deadly','debris','decent','deepen','deeply','defeat','defend','deject','delist',
  'deluge','derive','detour','detest','devoid','devout','differ','dilute','dimple',
  'dispel','disarm','divert','divide','domino','dotted','dottle','doting','dredge',
  'dressy','driven','drizzle','drudge','dryly','dungeon','efface','effect','eighth',
  'either','eleven','embark','embody','emerge','encode','endure','engulf','enlist',
  'enrage','ensure','escape','evolve','exceed','excite','excuse','exempt','exhale',
  'expand','expert','expire','extend','fabled','factual','famine','fatten','feeble',
  'ferret','fervor','fester','fickle','fierce','filter','fissure','fixing','fizzle',
  'flaked','flashy','flaunt','flavor','flecks','fledge','flimsy','flirts','floats',
  'florid','floury','fluffy','forbid','frenzy','frolic','frozen','frugal','fruity',
  'fumble','galley','gazing','gentle','gifted','giggle','gilded','gloomy','gobble',
  'goblet','godsend','gossip','gotten','gravel','greedy','grieve','grinds','grumpy',
  'guided','gutter','hamlet','hamper','happen','hardy','harken','harden','hatred',
  'hazard','hollow','honest','horror','humble','hunger','hustle','ignite','illusion',
  'impact','impede','impose','injury','insult','intend','invade','invent','invoke',
  'irk','jagged','jiggle','jocund','joyful','joyous','jungle','junior','keenly',
  'kidnap','kindly','knight','knobby','knocks','latest','latent','lather','laughs',
  'launch','lavish','leaden','league','leaping','leaves','legend','limber','linear',
  'linger','liquid','loosen','loudly','luring','malice','mangle','marvel','meadow',
  'meddle','menace','mentor','merest','method','mingle','mishap','misuse','mobile',
  'modest','molten','mortal','mostly','mugger','musing','mystic','nearly','needed',
  'nestle','nibble','nicely','nimble','nimbly','nodded','noises','nudge','nuzzle',
  'object','oddity','offend','omit','opener','oppose','ordeal','outcry','outfit',
  'outlet','outrun','outset','parent','parted','partly','patter','paving','pearly',
  'pebble','petite','pierce','pillar','plenty','plucky','plunder','poetic','pointed',
  'portal','potent','potter','prefer','priest','proper','pummel','raging','rancid',
  'rankle','rarely','ravage','reckless','recoil','refine','refuel','reject',
  'remake','rental','repeat','rescue','resist','rested','riddle','ripple','robust',
  'rocket','rotten','ragged','saddle','scarce','sculpt','seldom','settle','shoddy',
  'shrewd','shimmer','shiver','silken','simmer','single','skimpy','sleepy',
  'sneaky','solemn','sparks','spiral','splash','spooky','sprout','squall','squeak',
  'stains','starve','sterile','stifle','stoker','streak','stride','strife','strive',
  'strung','stumble','subtle','suitor','sunset','swiftly','tangle','tangled','teethe',
  'tender','tenfold','tether','thorny','thatch','thrice','throb','tirade','toggle',
  'trance','trickle','trudge','turnip','twitch','uncanny','uneven','unfair','untold',
  'untrue','unveil','upbeat','update','uplift','utmost','valiantly','vanish','vanquish',
  'vastly','vendor','vessel','visage','vivid','vocals','wander','wanted','wayward',
  'whimsy','whiten','widget','wither','wobble','wonder','worthy','yeoman','zealous',
  // 7-letter additions
  'abandon','abolish','absolve','acclaim','accrued','achieve','acquire','address',
  'advance','adverse','advised','advised','affable','against','ageless','ailment',
  'already','amazing','amplify','ancient','another','anxious','anybody',
  'arrange','arrival','aspired','astound','attract','audible','balance','banquet',
  'bargain','beloved','brimming','bristle','broadly','brocade','bumbler','capital',
  'careful','central','ceramic','chaplain','charmed','classic','clamber','clarity',
  'clearly','climate','collect','combine','command','complex','concept','concern',
  'conduct','confirm','connect','counsel','courage','courtly','crumble','crusade',
  'current','custody','cycling','dashing','daunted','daylong','decided','declare',
  'defense','density','deposit','deserve','destroy','devoted','digital','disable',
  'discuss','distant','divided','dormant','durable','earnest','eastern','elderly',
  'enhance','evolve','excited','extreme','fearful','festive','finance','finding',
  'forward','fulfill','genuine','gladly','gratify','habitat','handful','harvest',
  'healthy','heroism','history','horizon','however','hundred','ignorant','imagine',
  'improve','include','initial','inspire','inviting','justify','knowing','largest',
  'leading','lengthy','liberal','liberty','limited','lineage','loyalty','magical',
  'maximum','measure','mention','message','mineral','mission','mixture','morning',
  'natural','network','nowhere','nuclear','officer','organic','outcome','outrage',
  'overrun','padlock','partial','passion','patient','pattern','perform',
  'popular','prestige','prevent','produce','program','protect','prudent','qualify',
  'quickly','rapidly','realize','require','resolve','retreat','revenue','rolling',
  'roughly','scenery','secured','sensibly','serious','shelter','silence','similar',
  'soldier','species','sterling','strange','succeed','suggest','support','surface',
  'survive','teacher','tonight','totally','trading','trouble','turning','typical',
  'unified','unknown','usually','village','violent','warrior','weather','western',
  'whether','without','working','writing','zealous',
  // 8-letter additions
  'absolute','abstract','accessed','accurate','achieved','actually','addition',
  'adequate','adjacent','advanced','affected','alliance','allowing','although',
  'altruism','analysis','ancestor','animated','announce','apparent','appetite','argument',
  'assembly','attached','balanced','baseline','becoming','behavior','blessing',
  'boundary','breaking','campaign','capacity','ceremony','champion','changing',
  'clearing','climbing','collapse','combined','complete','conceive','conflict',
  'consider','constant','consumed','continue','convince','creating','creature',
  'criteria','darkness','decision','declared','defeated','describe','detailed',
  'devoting','directly','disaster','distract','division','dominant','downfall',
  'dreaming','dwelling','enormous','entirely','entrance','equality','evaluate',
  'evidence','evolving','existing','explored','exposure','external','familiar',
  'fighting','finished','flexible','floating','focusing','followed','forecast',
  'fraction','fragment','freezing','frontier','function','generate','guardian',
  'guidance','heritage','hospital','identify','imagined','immortal','improved',
  'increase','indicate','inherent','innocent','isolated','judgment','language',
  'learning','location','maintain','manifest','material','maximize','medicine',
  'minister','momentum','movement','multiple','newcomer','northern','observed',
  'operated','overcome','powerful','practice','previous','probable','progress',
  'property','provided','pursuing','question','received','recovery','register',
  'regulate','rejected','relation','reliable','required','research','reserved',
  'resource','response','resulted','revision','rightful','sacrifice','scenario',
  'schedule','security','sequence','services','shifting','shoulder','skeleton',
  'sleeping','solution','somebody','somewhat','southern','speaking','specific',
  'standard','standing','starting','strategy','strength','struggle','stunning',
  'surprise','survival','symbolic','together','transfer','traveled','treasury',
  'uncommon','universe','unlikely','variable','watching','whatever','whenever',
  'yourself',
  // ── Extended dictionary part 2 ───────────────────────────────────────────────
  // Common verb forms (past tense / gerunds / 3rd person)
  'ached','acted','added','aimed','asked','baked','banned','barked','bathed',
  'beamed','begged','bent','biked','billed','binded','bit','bled','blew','blinded',
  'blocked','blown','boiled','bolted','bored','borrowed','bowed','boxed','bragged',
  'brewed','bribed','built','burned','called','calmed','camped','cared','carved',
  'cashed','cast','caught','chased','checked','chewed','choked','clapped','clicked',
  'climbed','clung','cooked','copied','counted','crawled','cried','crossed','crushed',
  'danced','dared','dealt','dived','dodged','doubted','dragged','dried','drove',
  'dumped','dusted','earned','erased','evaded','faced','failed','faked','fell',
  'filed','fired','flapped','flipped','flowed','flown','folded','forced','froze',
  'frosted','gained','grabbed','gripped','grown','guessed','guided','hailed',
  'handed','hauled','healed','heeded','helped','hid','hiked','hired','hoped',
  'howled','hunted','hurled','iced','joked','jumped','kicked','killed','landed',
  'lasted','laughed','led','leaped','lied','listed','lived','loaded','locked',
  'looked','loved','lowered','made','marched','matched','merged','missed','mixed',
  'moved','named','obeyed','opened','owned','packed','passed','paused','played',
  'pointed','poured','proved','pulled','punched','pushed','raised','reached',
  'replied','rested','risked','rolled','rowed','ruled','rushed','saved','sealed',
  'served','shook','shoved','showed','signed','skipped','slid','slipped','solved',
  'sorted','spent','stayed','stepped','stirred','stopped','stored','stretched',
  'struck','studied','suited','surfed','swam','swept','swore','taken','talked',
  'tested','thanked','threw','tied','timed','touched','tossed','tracked','traded',
  'tried','trusted','turned','used','waited','walked','wanted','warned','waved',
  'wept','wished','worked','worried','wrecked','yelled',
  // -ing forms
  'aching','acting','adding','aiding','aiming','baking','banning','barking','bathing',
  'beaming','begging','bending','biking','billing','biting','bleeding','blowing',
  'blocking','boiling','bolting','boring','bowing','boxing','brewing','building',
  'burning','calling','calming','camping','caring','carving','catching','chasing',
  'chewing','choking','clapping','clicking','climbing','cooking','copying','counting',
  'crawling','crossing','crushing','dancing','dealing','diving','dodging','doubting',
  'dragging','drifting','drying','driving','dumping','dusting','earning','escaping',
  'evading','failing','firing','flipping','flowing','folding','forcing','gaining',
  'grabbing','gripping','guessing','guiding','hauling','healing','helping','hiking',
  'hoping','howling','hunting','hurling','joking','jumping','kicking','killing',
  'landing','laughing','leading','leaving','living','loading','locking','looking',
  'loving','making','marching','matching','missing','mixing','moving','opening',
  'packing','passing','pausing','playing','pointing','pouring','proving','pulling',
  'punching','pushing','raising','reaching','resting','risking','rolling','rowing',
  'ruling','rushing','saving','sealing','serving','showing','skipping','sliding',
  'slipping','solving','sorting','staying','stepping','stirring','stopping','storing',
  'studying','surfing','swimming','sweeping','swearing','talking','testing','thanking',
  'throwing','timing','touching','tossing','tracking','trading','trying','trusting',
  'turning','waiting','walking','wanting','warning','waving','wishing','working',
  'worrying','yelling',
  // Common plural nouns
  'aces','ages','aids','aims','airs','alms','alps','amps','ants','apes','arcs',
  'ares','arks','arms','arts','aces','axes','bags','bans','bars','bats','bays',
  'beds','bets','bits','bogs','bows','boys','buds','bugs','buns','cars','cats',
  'cobs','cods','cogs','cops','cots','cows','cubs','cups','dabs','days','dens',
  'digs','dims','dips','dogs','dots','dubs','dues','duos','dyes','ears','eggs',
  'eels','elms','ends','eras','fads','fans','fees','figs','fins','fits','flies',
  'foes','fogs','foxes','furs','gaps','gases','gets','gigs','gins','gods','gums',
  'guns','guts','guys','hags','hams','hats','hens','hobs','hogs','hops','hubs',
  'hugs','huts','ills','imps','inks','ions','jabs','jags','jams','jars','jaws',
  'jets','jigs','jobs','jogs','jugs','kegs','kids','kits','labs','lags','laps',
  'legs','lids','lips','logs','lots','lugs','maps','mobs','mops','mugs','nabs',
  'nags','naps','nets','nips','nods','nuns','oars','oats','odds','odes','orbs',
  'ores','owls','pads','pans','paws','pays','peas','pegs','pens','pets','pigs',
  'pins','pits','pods','pops','pots','pubs','puns','pups','puts','rags','rams',
  'raps','rats','rays','rods','rows','rubs','rugs','rums','runs','sags','saps',
  'seas','sets','sins','sips','sits','skis','skies','sobs','sons','sows','spas',
  'spies','subs','sums','tabs','tads','tans','taps','tars','teas','tens','tins',
  'tips','toes','tops','tows','toys','tubs','tugs','urns','vans','vats','vows',
  'wads','wars','ways','webs','wigs','wins','wits','yaks','yams','yaps','yews','zoos',
  // 5-letter plurals and other forms
  'acres','aches','acids','ages','birds','boats','books','boots','boxes','boys',
  'boys','brands','cakes','calls','camps','cards','cares','cases','caves','cells',
  'cents','chars','chefs','chips','claps','clays','clips','coals','codes','coils',
  'coins','cones','cooks','cores','corns','costs','crabs','crabs','crews','crops',
  'crows','cubes','curls','dares','darts','dates','dawns','deals','deans','decks',
  'deeds','dents','dimes','docks','doves','drags','draws','drips','drops','drums',
  'dumps','dungs','dusts','earls','edges','exams','exits','fails','fakes','falls',
  'farms','feels','ferns','fills','films','finds','fires','firms','fishs','fists',
  'flaps','flaws','fleas','flies','flips','flops','flows','foams','folds','foods',
  'fools','fords','forks','forms','forts','fouls','frees','frogs','fumes','funds',
  'fuses','gales','games','gangs','gates','gears','germs','gifts','girls','gives',
  'globs','gnaws','goals','goats','goals','grabs','grins','grips','grogs','gulls',
  'gusts','hails','hairs','halls','halts','hands','hangs','hares','harps','hashs',
  'hauls','hawks','heads','heaps','hears','heats','heeds','heels','herds','heros',
  'hills','hints','hires','holds','holes','homes','hooks','horns','hoses','hosts',
  'howls','hulls','humps','hunts','hurts','ices','irons','isles','itches','jokes',
  'jolts','jumps','keeps','kills','kinds','kings','knobs','lacks','lakes','lambs',
  'lamps','lands','lanes','lards','lasts','leads','leafs','leaks','leans','leaps',
  'lends','lifts','limes','limps','lines','links','lions','lists','loads','loans',
  'locks','lofts','loons','loops','lords','lusts','mails','mains','makes','males',
  'malls','malts','marks','masts','meals','means','meats','meets','melts','miles',
  'milks','mills','minds','mines','mints','misss','mists','modes','monks','moons',
  'moves','mules','musks','nails','names','nooks','notes','nouns','oaths','opens',
  'ovens','pains','pairs','pales','palms','pangs','paves','pecks','peels','peers',
  'pests','picks','piles','pines','pings','pinks','plans','plays','poems','poets',
  'poles','polls','pores','ports','poses','posts','pours','preps','preys','prods',
  'props','pulls','pumps','purrs','racks','ramps','rands','ranks','rants','reaps',
  'rests','rides','rifts','rings','riots','rises','risks','roads','robes','rocks',
  'roles','romps','ropes','roses','routs','rules','rumps','rushs','sages','sails',
  'sales','salts','sands','saves','seams','sells','sends','sheds','shins','ships',
  'shoes','shots','shows','sides','sighs','silks','sills','silos','sings','sinks',
  'sizes','skins','slabs','slaps','slims','slits','slugs','slums','snags','snaps',
  'snips','snobs','snubs','soaks','soars','socks','soils','songs','soots','sores',
  'sorts','souls','soups','spans','spars','spins','spits','spots','spurs','stabs',
  'stags','stars','stays','stems','steps','stews','stirs','stops','stubs','studs',
  'suits','surfs','swaps','swats','swigs','tails','tales','tames','tanks','tapes',
  'tarts','tasks','tears','tents','terms','tests','ticks','tiles','tills','times',
  'tires','toads','tongs','tools','toses','tours','towns','traps','trays','treks',
  'trips','tubes','tucks','tufts','turns','tusks','types','urges','users','veils',
  'veins','vests','views','visas','voids','votes','wades','wages','wanes','waves',
  'weeds','wells','whims','whins','whips','wides','wills','wines','wings','wires',
  'wishs','wolfs','wombs','woods','wools','words','works','wrens','writs','yawns',
  'yells','zeros','zones','zooms',
  // Common 6-letter forms and words
  'ablest','absent','abused','abuses','across','acting','actors','actual','admits',
  'adorns','adults','aerial','afford','afield','agates','agents','agreed','agrees',
  'albums','alerts','aliens','alleys','allied','allies','allows','almond','amends',
  'angels','angers','angles','answer','appeals','arenas','argued','argues','arises',
  'arrays','artery','assets','avoids','babies','backed','badges','ballet','ballot',
  'banana','bandit','banker','banner','barely','barrel','basket','beards','beauty',
  'beaver','before','begins','belted','beside','better','beware','biases','bidded',
  'bitten','blades','blanks','blasts','blazes','bleeds','blends','blinks','blocks',
  'blooms','blouse','blunts','boards','boiled','booths','bribes','bricks','brings',
  'broken','brooks','brutes','builds','bulked','bullets','bursts','buyers','cables',
  'called','camera','cancel','candle','canopy','canter','capped','catchy','cattle',
  'caused','ceases','chains','chance','chants','charms','charts','cheers','chisel',
  'cities','claims','clears','cliffs','clocks','clones','closed','clouds','clowns',
  'coasts','colors','cooled','copier','copies','corner','costly','crafts','cramped',
  'cranes','craved','craves','crazed','crooks','curves','cutout','cycles','damped',
  'dancer','dances','daring','darted','deaths','delays','demons','denied','deputy',
  'dipped','direct','dished','dishes','donkey','dotted','doubts','dozens','drinks',
  'drives','drones','droops','droves','dumped','dunked','easier','eating','eighth',
  'eleven','empire','enable','ending','enjoys','enters','eroded','errors','evenly',
  'events','evicts','exiles','exists','expand','expire','extends','extras','fables',
  'fairer','fallen','famous','fasted','faults','feasts','fences','fetish','fevers',
  'fibbed','fields','fights','filled','finder','finely','finest','firing','fixing',
  'fizzes','flagged','flames','flings','flirts','floats','floors','flours','flowed',
  'fluent','foiled','formal','formed','fought','fright','frozen','fruits','fueled',
  'gained','galaxy','gleams','glides','glooms','glossy','gloves','graced','grades',
  'grains','grants','grasps','greedy','greens','griefs','grimes','grinds','groans',
  'gropes','groups','gravel','grumps','guests','guides','guilds','guilts','halved',
  'halves','hasted','hatred','haunts','healed','hearts','heated','helped','heroes',
  'honors','hosted','houses','hugely','humors','hustle','images','immune','impose',
  'inches','indeed','infant','inform','inject','inland','inputs','inside','intent',
  'irking','jammed','joined','joking','joying','judges','juiced','juices','junior',
  'labels','lacked','landed','larger','lasted','laughs','lagged','layers','leaves',
  'legged','lesser','likely','linker','lining','listed','lively','loaded','lonely',
  'longer','looted','losses','lovely','lovers','lowest','luggage','mainly','making',
  'malted','manned','marvel','mashed','masked','melted','merged','mocked','models',
  'modest','molded','mortal','motley','mounts','moaned','mulled','nailed','nearly',
  'nobles','nobler','noises','obeyed','object','offers','opened','orders','others',
  'ounces','ousted','packed','paired','papers','passed','paused','placed','places',
  'plague','planes','plants','played','plucked','plunks','pointed','poised','polled',
  'pooled','pounds','prayer','prefer','pretty','probed','proved','pulled','pumped',
  'pushed','raging','ranged','rained','raised','rarely','ravage','rebels','relied',
  'rented','repeat','repaid','retake','rolled','rounds','royals','rubbed','ruined',
  'rushed','safely','sailed','salted','sanded','sealed','seeded','seemed','seized',
  'senior','served','setups','sewing','shaken','shaped','shared','shined','showed',
  'shrimp','silent','silver','simple','simply','single','sister','skills','skinny',
  'skirts','slated','slaved','sledge','sliced','slimes','slinky','slopes','sloths',
  'slouch','slowly','smiled','smoked','snails','snaked','sneaks','snored','soared',
  'solved','sorted','sought','spaced','spared','sparks','speaks','speeds','spends',
  'spiced','spires','spites','splits','spoken','sports','sprays','stands','stolen',
  'stored','storms','street','struck','styles','supply','surged','surely','swamps',
  'swears','swirls','tagged','taking','tariff','taught','teared','teased','temple',
  'tested','thinking','thrice','timing','tipped','titled','tokens','traced','traded',
  'trails','trains','traits','travel','triple','troops','troves','trucks','trumps',
  'trunks','trusts','truths','tugged','tumors','tuning','twists','typing','unions',
  'unites','unread','update','upheld','upkeep','uproot','upheld','uphold','values',
  'varied','varies','veered','verbal','viewed','visits','voiced','voices','voting',
  'wagers','wagged','wasted','waters','waving','weaker','weekly','welded','widely',
  'wilder','willed','wisest','wolves','wonders','wooden','worked','worlds','worths',
  'wounds','writers','yearly','zigzag',
];

// Build a single Set for O(1) lookups — includes base words + all category words
const VALID_WORDS = (() => {
  const set = new Set(VALID_WORDS_LIST.map(w => w.toLowerCase()));
  for (const cat of Object.values(COMBAT_CATEGORIES)) {
    for (const w of cat.words) set.add(w.toLowerCase());
  }
  return set;
})();

/**
 * Check if a word is valid.
 * @param {string} word
 * @returns {boolean}
 */
function isValidWord(word) {
  return word.length >= 2 && VALID_WORDS.has(word.toLowerCase());
}

/**
 * Get the combat category (if any) for a word.
 * Returns the first matching category key or null.
 * @param {string} word
 * @returns {string|null}
 */
function getWordCategory(word) {
  const lower = word.toLowerCase();
  for (const [key, cat] of Object.entries(COMBAT_CATEGORIES)) {
    if (cat.words.has(lower)) return key;
  }
  return null;
}

/**
 * Return the full category object for a category key.
 * @param {string} key
 * @returns {object|null}
 */
function getCategoryData(key) {
  return COMBAT_CATEGORIES[key] || null;
}

/**
 * Check whether a word can be formed from the given tile letters.
 * @param {string} word
 * @param {string[]} tileLetters  — array of uppercase letter strings, may include '★' for wild
 * @returns {boolean}
 */
function canFormWord(word, tileLetters) {
  const available = [...tileLetters.map(l => l.toUpperCase())];
  for (const ch of word.toUpperCase()) {
    const idx = available.indexOf(ch);
    if (idx === -1) {
      const wildIdx = available.indexOf('★');
      if (wildIdx === -1) return false;
      available.splice(wildIdx, 1);
    } else {
      available.splice(idx, 1);
    }
  }
  return true;
}
